import { NextResponse } from "next/server";

export const revalidate = 86400; // Revalidate once per day

// Comprehensive list of Croatian cities with supermarkets
const CROATIAN_CITIES = [
  "Zagreb",
  "Split",
  "Rijeka",
  "Osijek",
  "Zadar",
  "Slavonski Brod",
  "Pula",
  "Karlovac",
  "Sisak",
  "Varaždin",
  "Šibenik",
  "Dubrovnik",
  "Bjelovar",
  "Koprivnica",
  "Čakovec",
  "Vinkovci",
  "Vukovar",
  "Požega",
  "Virovitica",
  "Petrinja",
  "Gospić",
  "Makarska",
  "Samobor",
  "Velika Gorica",
  "Zaprešić",
  "Sesvete",
  "Ivanić Grad",
  "Đurđevac",
  "Križevci",
  "Krapina",
  "Čazma",
  "Kutina",
  "Novska",
  "Nova Gradiška",
  "Đakovo",
  "Vinkovci",
  "Županja",
  "Slatina",
  "Orahovica",
  "Pakrac",
  "Daruvar",
  "Grubišno Polje",
  "Garešnica",
  "Beli Manastir",
  "Valpovo",
  "Donji Miholjac",
  "Našice",
  "Ogulin",
  "Delnice",
  "Crikvenica",
  "Senj",
  "Otočac",
  "Knin",
  "Sinj",
  "Imotski",
  "Metković",
  "Ploče",
  "Korčula",
  "Hvar",
  "Rovinj",
  "Poreč",
  "Umag",
  "Pazin",
  "Labin",
  "Buzet",
  "Buje",
  "Novigrad",
  "Vir",
  "Biograd na Moru",
  "Benkovac",
  "Obrovac",
  "Drniš",
  "Trogir",
  "Kaštela",
  "Solin",
  "Omiš",
  "Brela",
  "Baška Voda",
  "Podgora",
  "Gradac",
  "Vrgorac",
  "Trilj",
  "Klis",
  "Dugopolje",
  "Zlatar Bistrica",
  "Donja Stubica",
  "Oroslavje",
  "Pregrada",
  "Klanjec",
  "Zabok",
  "Sveti Ivan Zelina",
  "Dugo Selo",
  "Vrbovec",
  "Bjelovar",
  "Čazma",
  "Daruvar",
  "Grubišno Polje",
  "Garešnica",
  "Pakrac",
  "Lipik",
  "Kutjevo",
  "Pleternica",
  "Đakovo",
  "Vrbanja",
  "Županja",
  "Vinkovci",
  "Ilok",
  "Vukovar",
  "Borovo",
  "Nuštar",
  "Tovarnik",
  "Nijemci",
  "Lovas",
  "Tompojevci",
  "Stari Mikanovci",
  "Andrijaševci",
  "Privlaka",
  "Vođinci",
  "Rokovci",
  "Otok",
  "Drenovci",
  "Gunja",
  "Bošnjaci",
  "Cerna",
  "Stari Jankovci",
  "Novi Jankovci",
  "Markušica",
  "Tordinci",
  "Negoslavci",
  "Trpinja",
  "Bobota",
  "Vera",
  "Pačetin",
  "Petrovci",
  "Orolik",
  "Slakovci",
  "Šidski Banovci",
  "Lovran",
  "Opatija",
  "Matulji",
  "Kastav",
  "Viškovo",
  "Čavle",
  "Kostrena",
  "Bakar",
  "Kraljevica",
  "Crikvenica",
  "Novi Vinodolski",
  "Senj",
  "Novalja",
  "Rab",
  "Krk",
  "Malinska",
  "Punat",
  "Baška",
  "Vrbnik",
  "Omišalj",
  "Njivice",
  "Dobrinj",
  "Šilo",
  "Klimno",
  "Soline",
  "Risika",
  "Garica",
  "Kornić",
  "Vrh",
  "Draga Bašćanska",
  "Jurandvor",
  "Batomalj",
  "Brzac",
  "Linardići",
  "Milohnići",
  "Muraj",
  "Pinezići",
  "Skrbčići",
  "Vrh",
  "Žgaljići",
  "Žestilac",
];

// Deduplicate and sort
const uniqueCities = [...new Set(CROATIAN_CITIES)].sort((a, b) =>
  a.localeCompare(b, "hr")
);

export async function GET() {
  return NextResponse.json({
    cities: uniqueCities,
  });
}
